#if !canImport(ObjectiveC)
import XCTest

extension RunnerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RunnerTests = [
        ("testLongRunning", testLongRunning),
        ("testSyncNonZeroStatus", testSyncNonZeroStatus),
        ("testSyncZeroStatus", testSyncZeroStatus),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    [
        testCase(RunnerTests.__allTests__RunnerTests),
    ]
}
#endif
