#if !canImport(ObjectiveC)
import XCTest

extension RunnerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RunnerTests = [
        ("testSync", testSync),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RunnerTests.__allTests__RunnerTests),
    ]
}
#endif
